<?php

/**
 * Drupal Hooks
 */

function pdf_warp_form_alter(&$form, $form_state, $form_id) {
  if (strpos($form_id, 'uc_product_add_to_cart_form') !== false) {
    $form['to_pdf_button'] = array(
      '#type' => 'submit',
      '#value' => t('To PDF'),
      '#submit' => array('pdf_warp_product_page')
    );
  }
}

function pdf_warp_theme(){
  return array(
    'pdf_warp_product' => array (
      'template' => 'pdf-warp-product'
    )
  );
}

function pdf_warp_product_page() {
  drupal_add_library('angularjs', 'angularjs');
  $path = drupal_get_path('module', 'pdf_warp');
  drupal_add_js($path, '/pdf_Warp.js');
  return theme('pdf_warp_product');
}